### ISSUE TITLE
No weapons and no problem

### ISSUE THREAD

**Issue by dok441** [TimGoll/ttt2-role_mark#9]
Is not issue weapons paintball player.

**Comment by TimGoll** [comment]
I don't know what you try to say but the marker does get his weapon. If he doesn't the slots are already used or your server has an addom interfering with the marker

**Comment by TimGoll** [comment]
Have you tested it on multiplayer or singleplayer? 
As far as I know giving weapons to players in a singleplayer world does not work since the function uses the steamID internally. 
Additionally it is a known problem of GMOD that sometimes there are problems with the weapon giving, see here: https://github.com/Facepunch/garrysmod/blob/master/garrysmod/gamemodes/terrortown/gamemode/weaponry.lua#L297

**Comment by dok441** [comment]
Multiplayer, with other roles there is no such problem, you may need to think

**Comment by TimGoll** [comment]
That's just a coincidence. The jackal, marker and priest all use the same code. This problem is not related to the marker, but to a general GMOD problem. 
This is underlined by the fact that it is working for everybody else but you.

**Comment by dok441** [comment]
Okay, if that's the case.

**Comment by TimGoll** [comment]
it is

**Comment by TimGoll** [comment]
![image](https://user-images.githubusercontent.com/13639408/60905453-6a4fd180-a275-11e9-97a9-b6241b5fe2fe.png)

I just tested it and it works without a problem

**Comment by dok441** [comment]
I understand, I just reported the problem which see not just 1.
